const sections = [
{
"type":"direct",
"label":"Home",
"url":"sections/home.html"
},
{
"type":"tree",
"label":"Docs",
"tree":[
  {
  "type":"direct",
  "label":"Overview",
  "url":"sections/docs/intro.html",
  },
  {
  "type":"direct",
  "label":"Installation",
  "url":"sections/docs/install.html"
  },
  {
  "type":"direct",
  "label":"Structure",
  "url":"sections/docs/structure.html"
  },
  {
  "type":"direct",
  "label":"Usage",
  "url":"sections/docs/howto.html"
  },
  {
  "type":"direct",
  "label":"Insights & Dependencies",
  "url":"sections/docs/insight.html"
  }
]
},
{
"type":"tree",
"label":"Py Generator",
"tree":[
  {
  "type":"direct",
  "label":"Usage",
  "url":"sections/pygen/pygen.html"
  }
]
}
]